[package]
name = "git-ignore-generator"
version = "0.2.0"
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
homepage = "https://github.com/sondr3/git-ignore"
description = "Quickly and easily fetch .gitignore templates from www.gitignore.io"
repository = "https://github.com/sondr3/git-ignore"
documentation = "https://github.com/sondr3/git-ignore"
readme = "README.md"
license = "GPL-3.0-or-later"
edition = "2018"

[[bin]]
name = "git-ignore"
path = "src/main.rs"

[features]
fail-on-warnings = []

[dependencies]
structopt = "0.2"
reqwest = "0.9"