[package]
name = "git-ignore-generator"
version = "1.0.0"
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
homepage = "https://github.com/sondr3/git-ignore"
description = "Quickly and easily fetch .gitignore templates from www.gitignore.io"
repository = "https://github.com/sondr3/git-ignore"
documentation = "https://github.com/sondr3/git-ignore"
readme = "README.md"
license = "GPL-3.0-or-later"
edition = "2018"
build = "build.rs"

[[bin]]
name = "git-ignore"
path = "src/main.rs"

[profile.release]
lto = "fat"

[dependencies]
structopt = "0.3.14"
attohttpc = { version = "0.13.0", features = ["json", "tls-rustls"] }
directories = "2.0.2"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"
colored = "1.9.3"

[build-dependencies]
man = "0.3.0"
