[package]
name = "git-ignore-generator"
version = "1.1.1"
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
homepage = "https://github.com/sondr3/git-ignore"
description = "Quickly and easily fetch .gitignore templates from www.gitignore.io"
repository = "https://github.com/sondr3/git-ignore"
documentation = "https://github.com/sondr3/git-ignore"
readme = "README.md"
license = "GPL-3.0-or-later"
edition = "2018"
build = "build.rs"

[[bin]]
name = "git-ignore"
path = "src/main.rs"

[profile.release]
lto = "fat"

[dependencies]
structopt = "0.3.21"
attohttpc = { version = "0.16.3", default-features = false, features = ["json", "compress", "tls-rustls"] }
directories = "3.0.1"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
colored = "2.0.0"

[build-dependencies]
man = "0.3.0"
