[package]
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
build = "build.rs"
description = "Quickly and easily fetch .gitignore templates from www.gitignore.io"
documentation = "https://github.com/sondr3/git-ignore"
edition = "2021"
homepage = "https://github.com/sondr3/git-ignore"
license = "GPL-3.0-or-later"
name = "git-ignore-generator"
readme = "README.md"
repository = "https://github.com/sondr3/git-ignore"
version = "1.1.2"

[[bin]]
name = "git-ignore"
path = "src/main.rs"

[profile.release]
lto = "fat"

[dependencies]
attohttpc = { version = "0.18.0", default-features = false, features = ["json", "compress", "tls-rustls"] }
clap = "3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"
colored = "2.0.0"
directories = "4.0.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
toml = "0.5"

[build-dependencies]
man = "0.3.0"
clap = "3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"
